export const USER_DATA_SAVE = "USER_DATA_SAVE";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const LOADING = "LOADING";
export const SAVE_CONFIG_DATA = "SAVE_CONFIG_DATA";
export const LOGOUT = "LOGOUT";
export const SAVE_LANGUAGE = "SAVE_LANGUAGE";

/*ADMIN USER*/
export const ADD_ADMIN_USER = "ADD_ADMIN_USER";
export const ADMIN_USER_SAVE = "ADMIN_USER_SAVE";

export const INTRO_SLIDER = "INTRO_SLIDER";

//company constants
export const ADD_COMPANY_DRIVER = "ADD_COMPANY_DRIVER";
export const UPDATE_COMPANY_DRIVER = "UPDATE_COMPANY_DRIVER";
export const GET_COMPANY_DRIVER = "GET_COMPANY_DRIVER";
export const DELETE_COMPANY_DRIVER = "DELETE_COMPANY_DRIVER";

export const ADD_COMPANY_VEHICLE = "ADD_COMPANY_VEHICLE";
export const UPDATE_COMPANY_VEHICLE = "UPDATE_COMPANY_VEHICLE";
export const GET_COMPANY_VEHICLE = "GET_COMPANY_VEHICLE";
export const DELETE_COMPANY_VEHICLE = "DELETE_COMPANY_VEHICLE";

export const ADD_COMPANY_WAREHOUSE = "ADD_COMPANY_WAREHOUSE";
export const UPDATE_COMPANY_WAREHOUSE = "UPDATE_COMPANY_WAREHOUSE";
export const GET_COMPANY_WAREHOUSE = "GET_COMPANY_WAREHOUSE";
export const DELETE_COMPANY_WAREHOUSE = "DELETE_COMPANY_WAREHOUSE";

export const GET_METRIC_LISTING = "GET_METRIC_LISTING";
export const GET_VEHICLE_LISTING = "GET_VEHICLE_LISTING";
export const GET_WAREHOUSE_LIST = "GET_WAREHOUSE_LIST";

export const SAVE_COMPANY_DETAIL = "SAVE_COMPANY_DETAIL";
export const UPDATE_COMPANY_DETAIL = "UPDATE_COMPANY_DETAIL";
export const CHANGE_COMPANY_PASSWORD = "CHANGE_COMPANY_PASSWORD";
export const WAREHOUSE_CITY_LISTING = "WARE_HOUSE_CITY_LISTING";

export const WAREHOUSE_CITY_FILTER = "WAREHOUSE_CITY_FILTER";
export const WAREHOUSE_TYPE_FILTER = "WAREHOUSE_TYPE_FILTER";
export const WAREHOUSE_METRIC_TYPE_FILTER = "WAREHOUSE_METRIC_TYPE_FILTER";

export const WAREHOUSE_DETAILS = "WAREHOUSE_DETAILS";

export const GET_REQUEST_LISTING = "GET_REQUEST_LISTING";
export const GET_CERTIFICATION_LISTING = "GET_CERTIFICATION_LISTING";
export const CERTIFICATE_TYPE_FILTER = "CERTIFICATE_TYPE_FILTER";

// checkout
export const SAVE_QUOTE_ITEM = "SAVE_QUOTE_ITEM";
export const GET_ORDER_LISTING = "GET_ORDER_LISTING";

// vehicle
//export const GET_VEHICLE_LIST = 'GET_VEHICLE_LIST';
export const VEHICLE_CITY_LISTING = "VEHICLE_CITY_LISTING";
export const VEHICLE_CITY_FILTER = "VEHICLE_CITY_FILTER";
export const VEHICLE_TYPE_FILTER = "VEHICLE_TYPE_FILTER";
export const VEHICLE_METRIC_TYPE_FILTER = "VEHICLE_METRIC_TYPE_FILTER";
export const VEHICLE_DETAILS = "VEHICLE_DETAILS";
export const VEHICLE_CERTIFICATE_TYPE_FILTER =
  "VEHICLE_CERTIFICATE_TYPE_FILTER";
export const VEHICLE_TRUCK_TYPE_FILTER = "VEHICLE_TRUCK_TYPE_FILTER";
export const VEHICLE_DATE_FILTER = "VEHICLE_DATE_FILTER";
